### ISSUE TITLE
VersionNotFoundError: Version `https://cdn.sheetjs.com/xlsx-0.20.0/xlsx-0.20.0.tgz` for package `xlsx` could not be found 

### ISSUE THREAD

**Issue by fhg-isi** [google/js-green-licenses#222]
In my package.json I have following dependency:

"xlsx": "https://cdn.sheetjs.com/xlsx-0.20.0/xlsx-0.20.0.tgz"

xlsx is published under Apache 2.0 license. 

I included xlsx in packageAllowlist. Nevertheless I get

```
Error while checking xlsx@https://cdn.sheetjs.com/xlsx-0.20.0/xlsx-0.20.0.tgz:
  micat@0.0.1 -> xlsx@https://cdn.sheetjs.com/xlsx-0.20.0/xlsx-0.20.0.tgz

VersionNotFoundError: Version `https://cdn.sheetjs.com/xlsx-0.20.0/xlsx-0.20.0.tgz` for package `xlsx` could not be found
    at packageJson (C:\python_env\App\WinPython\n\node_modules\js-green-licenses\node_modules\package-json\index.js:83:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async LicenseChecker.checkLicenses (C:\python_env\App\WinPython\n\node_modules\js-green-licenses\build\src\checker.js:237:26)
    at async LicenseChecker.checkLicensesForDeps (C:\python_env\App\WinPython\n\node_modules\js-green-licenses\build\src\checker.js:256:13)
    at async LicenseChecker.checkPackageJson (C:\python_env\App\WinPython\n\node_modules\js-green-licenses\build\src\checker.js:290:9)
    at async LicenseChecker.checkPackageJsonContent (C:\python_env\App\WinPython\n\node_modules\js-green-licenses\build\src\checker.js:300:13)
    at async LicenseChecker.checkLocalDirectory (C:\python_env\App\WinPython\n\node_modules\js-green-licenses\build\src\checker.js:360:13)
    at async main (C:\python_env\App\WinPython\n\node_modules\js-green-licenses\build\src\cli.js:65:9)
```

**Comment by Mehonoshin** [comment]
I have a similar issue but for other packages. Any workaround?
